kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: fisc
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://fisc-registry:5000"]  
